# Generated by Django 4.2.3 on 2023-07-19 16:18

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('clicked', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
