# Generated by Django 4.2.3 on 2023-07-20 11:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.CharField(default=api.models.generate_uuid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
