# Generated by Django 4.2.3 on 2023-07-20 23:19

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(default=page.models.generate_uuid, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('clicked', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
